# Generated by Django 5.1.7 on 2025-05-06 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_missing_profiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
