"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path
from urllib.parse import urlparse

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("ENVIRONMENT") == "development"

# SECURITY WARNING: keep the secret key used in production secret!
_secret = (os.environ.get("DJANGO_SECRET_KEY") or "").strip()
if _secret:
    SECRET_KEY = _secret
elif DEBUG:
    SECRET_KEY = "django-insecure-local-development-only-not-for-production"
else:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY must be set when ENVIRONMENT is not 'development'."
    )

IS_PRODUCTION = os.environ.get("ENVIRONMENT") == "production" or os.environ.get("DJANGO_ENV") == "production"
TRUST_BEHIND_PROXY = os.environ.get("TRUST_BEHIND_PROXY", "").lower() in ("1", "true", "yes")


def _database_url_raw():
    return (os.environ.get("DATABASE_URL") or "").strip().lstrip("\ufeff")


def _is_postgres_database_url(url: str) -> bool:
    if not url or url.lower().startswith("sqlite:"):
        return False
    scheme = urlparse(url).scheme.lower()
    if not scheme:
        return False
    base = scheme.split("+", 1)[0]
    return base in ("postgres", "postgresql", "pgsql", "postgis")


_db_url = _database_url_raw()


if IS_PRODUCTION or _is_postgres_database_url(_db_url):
    ALLOWED_HOSTS = [
        h.strip()
        for h in os.environ.get("ALLOWED_HOSTS", "").split(",")
        if h.strip()
    ]
    if not ALLOWED_HOSTS:
        raise ValueError("ALLOWED_HOSTS must be set in production when using DATABASE_URL")
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "false").lower() in ("1", "true", "yes")
    CSRF_TRUSTED_ORIGINS = [
        o.strip()
        for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
        if o.strip()
    ]
    if TRUST_BEHIND_PROXY:
        SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
        USE_X_FORWARDED_HOST = True
    if SECURE_SSL_REDIRECT:
        SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000"))
        SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get(
            "SECURE_HSTS_INCLUDE_SUBDOMAINS", "true"
        ).lower() in ("1", "true", "yes")
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"
else:
    ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0').split(',')
    SECURE_SSL_REDIRECT = False
    CSRF_TRUSTED_ORIGINS = []

# Google Maps API Key
GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY', '')

# django-cors-headers is installed but CorsMiddleware is intentionally omitted — the app is same-origin.
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "180/minute",
        "user": "360/minute",
        "suggestions": "15/minute",
        "google_track": "60/minute",
    },
}


# Application definition

INSTALLED_APPS = [
    "whitenoise.runserver_nostatic",

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',
    'django_redis',

    'schools',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Before CommonMiddleware: map pod / cluster IP Host headers to K8S_INTERNAL_HOST_FALLBACK (default 127.0.0.1).
    'config.middleware.RewriteInternalKubernetesHostMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'schools.middleware.GoogleAPITrackingMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'schools' / 'templates',
            BASE_DIR / 'users' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.settings.google_maps_api_key',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if IS_PRODUCTION and not _is_postgres_database_url(_db_url):
    raise ImproperlyConfigured(
        "ENVIRONMENT=production requires DATABASE_URL (postgresql://…). "
        "Check the app Secret (e.g. destino-docente-app-env) and that the web Deployment "
        "uses envFrom.secretRef with that Secret."
    )
elif _is_postgres_database_url(_db_url):
    ssl_require = os.environ.get("DATABASE_SSL_REQUIRE", "false").lower() in ("1", "true", "yes")
    DATABASES = {
        "default": dj_database_url.parse(
            _db_url,
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=ssl_require,
        ),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = "static/"
# Manifest storage requires `collectstatic` + staticfiles.json; local `runserver` usually skips that → 500 on {% static %}.
if DEBUG:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    WHITENOISE_KEEP_ONLY_HASHED_FILES = False
else:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    WHITENOISE_KEEP_ONLY_HASHED_FILES = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

_DETAIL_LOG_LEVEL = "DEBUG" if DEBUG else "INFO"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "level": "ERROR",
        },
        "django.contrib.sessions": {
            "handlers": ["console"],
            "level": _DETAIL_LOG_LEVEL,
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console"],
            "level": _DETAIL_LOG_LEVEL,
            "propagate": False,
        },
        "django.mail": {
            "handlers": ["console"],
            "level": _DETAIL_LOG_LEVEL,
            "propagate": False,
        },
        "schools": {
            "handlers": ["console"],
            "level": _DETAIL_LOG_LEVEL,
            "propagate": False,
        },
        "users": {
            "handlers": ["console"],
            "level": _DETAIL_LOG_LEVEL,
            "propagate": False,
        },
    },
}

LOGIN_URL = '/usuarios/conectarse/'
LOGIN_REDIRECT_URL = '/usuarios/panel/'
LOGOUT_REDIRECT_URL = '/'


def _env_bool(key: str, *, default: bool) -> bool:
    value = os.environ.get(key)
    if value is None or value == "":
        return default
    return value.lower() in ("1", "true", "yes", "on")


# Session settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# Over HTTP, browsers ignore Secure cookies unless these are false (homelab without TLS).
SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", default=not DEBUG)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# Email settings
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'sandbox.smtp.mailtrap.io')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@destino-docente.org')
CONTACT_EMAIL = os.environ.get('CONTACT_EMAIL', '')

# Add context processor for Google Maps API key
def google_maps_api_key(request):
    return {'google_maps_api_key': GOOGLE_MAPS_API_KEY}

SITE_URL = os.environ.get('SITE_URL', 'http://127.0.0.1:8000')

# hCaptcha settings
HCAPTCHA_SITE_KEY = os.environ.get('HCAPTCHA_SITE_KEY', '')  # Replace with your hCaptcha site key
HCAPTCHA_SECRET_KEY = os.environ.get('HCAPTCHA_SECRET_KEY', '')  # Replace with your hCaptcha secret key

_redis_url = (os.environ.get("REDIS_URL") or os.environ.get("VALKEY_URL") or "").strip()
if _redis_url:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": _redis_url,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        }
    }
