# Generated by Django 5.1.7 on 2025-05-03 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='Fax')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal code')),
                ('municipality', models.CharField(db_index=True, max_length=100, verbose_name='Municipality')),
                ('province', models.CharField(db_index=True, max_length=100, verbose_name='Province')),
                ('autonomous_community', models.CharField(db_index=True, max_length=100, verbose_name='Autonomous community')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('sub_region', models.CharField(max_length=100, verbose_name='Sub-region')),
                ('locality', models.CharField(max_length=100, verbose_name='Locality')),
                ('country', models.CharField(default='España', max_length=100, verbose_name='Country')),
                ('nature', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], db_index=True, max_length=50, verbose_name='Nature')),
                ('is_concerted', models.BooleanField(default=False, verbose_name='Is concerted')),
                ('center_type', models.CharField(db_index=True, max_length=50, verbose_name='Center type')),
                ('generic_name', models.CharField(max_length=255, verbose_name='Generic name')),
                ('services', models.JSONField(default=dict, verbose_name='Services')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'schools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImpartedStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('degree', models.CharField(blank=True, max_length=255, null=True, verbose_name='Degree')),
                ('family', models.CharField(blank=True, max_length=255, null=True, verbose_name='Family')),
                ('modality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Modality')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Study',
                'verbose_name_plural': 'Studies',
                'db_table': 'imparted_studies',
                'indexes': [models.Index(fields=['degree'], name='imparted_st_degree_5448f0_idx'), models.Index(fields=['family'], name='imparted_st_family_74c878_idx'), models.Index(fields=['modality'], name='imparted_st_modalit_492f05_idx')],
            },
        ),
        migrations.CreateModel(
            name='SchoolEditSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Postal code')),
                ('municipality', models.CharField(blank=True, max_length=100, verbose_name='Municipality')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Province')),
                ('autonomous_community', models.CharField(blank=True, max_length=100, verbose_name='Autonomous community')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_suggestions', to='schools.school')),
            ],
            options={
                'verbose_name': 'School Edit Suggestion',
                'verbose_name_plural': 'School Edit Suggestions',
                'db_table': 'school_edit_suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('study', models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.CASCADE, to='schools.impartedstudy')),
            ],
            options={
                'verbose_name': 'School Study',
                'verbose_name_plural': 'School Studies',
                'db_table': 'school_studies',
                'unique_together': {('school', 'study')},
            },
        ),
        migrations.AddField(
            model_name='school',
            name='studies',
            field=models.ManyToManyField(through='schools.SchoolStudy', to='schools.impartedstudy', verbose_name='Studies'),
        ),
        migrations.CreateModel(
            name='SchoolSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal code')),
                ('municipality', models.CharField(max_length=100, verbose_name='Municipality')),
                ('province', models.CharField(max_length=100, verbose_name='Province')),
                ('autonomous_community', models.CharField(max_length=100, verbose_name='Autonomous community')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('nature', models.CharField(choices=[('Público', 'Público'), ('Privado', 'Privado')], max_length=50, verbose_name='Nature')),
                ('is_concerted', models.BooleanField(default=False, verbose_name='Is concerted')),
                ('center_type', models.CharField(max_length=100, verbose_name='Center type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school')),
                ('studies', models.ManyToManyField(to='schools.impartedstudy')),
            ],
            options={
                'verbose_name': 'School Suggestion',
                'verbose_name_plural': 'School Suggestions',
                'db_table': 'school_suggestions',
                'ordering': ['-created_at'],
            },
        ),
    ]
