# Generated by Django 5.1.7 on 2025-05-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='school',
            name='autonomous_community',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Autonomous community'),
        ),
        migrations.AlterField(
            model_name='school',
            name='center_type',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Center type'),
        ),
        migrations.AlterField(
            model_name='school',
            name='country',
            field=models.CharField(blank=True, default='España', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='school',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='school',
            name='generic_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Generic name'),
        ),
        migrations.AlterField(
            model_name='school',
            name='is_concerted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is concerted'),
        ),
        migrations.AlterField(
            model_name='school',
            name='locality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Locality'),
        ),
        migrations.AlterField(
            model_name='school',
            name='municipality',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Municipality'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='school',
            name='nature',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], db_index=True, max_length=50, null=True, verbose_name='Nature'),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='school',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='school',
            name='province',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='school',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='school',
            name='services',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Services'),
        ),
        migrations.AlterField(
            model_name='school',
            name='sub_region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-region'),
        ),
        migrations.AlterField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
