# Generated by Django 5.1.7 on 2025-05-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_school_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='center_type',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Center type'),
        ),
        migrations.AlterField(
            model_name='school',
            name='nature',
            field=models.CharField(blank=True, choices=[('Centro público', 'Centro público'), ('Centro privado', 'Centro privado')], db_index=True, max_length=100, null=True, verbose_name='Nature'),
        ),
        migrations.AlterField(
            model_name='schoolsuggestion',
            name='nature',
            field=models.CharField(choices=[('Público', 'Público'), ('Privado', 'Privado')], max_length=100, verbose_name='Nature'),
        ),
    ]
