# Generated by Django 5.1.7 on 2025-04-16 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_schooleditsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooleditsuggestion',
            name='school',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='edit_suggestions', to='schools.school'),
        ),
    ]
