# Generated by Django 5.1.7 on 2025-05-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_school_center_type_alter_school_nature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='fax',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='schooleditsuggestion',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='schooleditsuggestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='schoolsuggestion',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='schoolsuggestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30, verbose_name='Status'),
        ),
    ]
