# Generated by Django 5.1.7 on 2025-05-06 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_school_fax_alter_school_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('radius', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Search radius')),
                ('results_count', models.IntegerField(default=0, verbose_name='Number of results')),
                ('provinces', models.JSONField(blank=True, default=list, verbose_name='Provinces')),
                ('school_types', models.JSONField(blank=True, default=list, verbose_name='School types')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Search timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search History',
                'db_table': 'search_history',
                'ordering': ['-timestamp'],
            },
        ),
    ]
