# Generated by Django 5.1.7 on 2025-04-16 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_schooleditsuggestion_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schooleditsuggestion',
            options={'managed': False},
        ),
    ]
