# Generated by Django 5.1.7 on 2025-04-16 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_alter_schooleditsuggestion_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='schooleditsuggestion',
            table='school_edit_suggestions',
        ),
    ]
