# Generated by Django 5.1.7 on 2025-05-06 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_searchhistory_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='radius',
        ),
    ]
