# Generated by Django 5.1.7 on 2025-04-16 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_alter_schooleditsuggestion_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolsuggestion',
            options={'managed': False, 'verbose_name': 'School Suggestion', 'verbose_name_plural': 'School Suggestions'},
        ),
    ]
