# Generated by Django 5.1.7 on 2025-04-16 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_alter_schoolsuggestion_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='schoolsuggestion',
            table='school_suggestions',
        ),
    ]
