# Generated by Django 5.1.7 on 2025-05-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_remove_searchhistory_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='autonomous_community',
            field=models.CharField(blank=True, max_length=100, verbose_name='Autonomous community'),
        ),
    ]
