# Generated by Django 5.1.7 on 2025-05-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_searchhistory_autonomous_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
