# Generated by Django 5.1.7 on 2025-05-08 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_searchhistory_is_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APICall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='The Google API endpoint that was called', max_length=255)),
                ('api_type', models.CharField(choices=[('directions', 'Google Directions API'), ('geocoding', 'Google Geocoding API'), ('places', 'Google Places API')], help_text='Type of Google API being called', max_length=50)),
                ('method', models.CharField(help_text='HTTP method used (GET, POST, etc.)', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the caller', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the API call was made')),
                ('response_status', models.IntegerField(help_text='HTTP status code of the response')),
                ('response_time', models.FloatField(help_text='Response time in milliseconds')),
                ('quota_remaining', models.IntegerField(blank=True, help_text='Remaining quota after the call', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who made the call, if authenticated', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['endpoint'], name='schools_api_endpoin_044c02_idx'), models.Index(fields=['api_type'], name='schools_api_api_typ_d13ee5_idx'), models.Index(fields=['user'], name='schools_api_user_id_45f930_idx'), models.Index(fields=['timestamp'], name='schools_api_timesta_f5012d_idx')],
            },
        ),
    ]
