# Generated by Django 5.1.7 on 2025-05-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_apicall'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicall',
            name='place_selected',
            field=models.BooleanField(blank=True, help_text='Whether a place was selected in this session', null=True),
        ),
        migrations.AddField(
            model_name='apicall',
            name='total_calls',
            field=models.IntegerField(blank=True, help_text='Total number of API calls in the session', null=True),
        ),
    ]
