# Generated by Django 5.1.7 on 2025-05-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_apicall_place_selected_apicall_total_calls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsuggestion',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='schoolsuggestion',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Longitude'),
        ),
    ]
