# Generated by Django 5.1.7 on 2025-05-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_alter_schoolsuggestion_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsuggestion',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='schoolsuggestion',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
