# Generated by Django 5.1.7 on 2025-06-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_alter_schooleditsuggestion_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='includes_travel_times',
            field=models.BooleanField(default=False, help_text='Whether this search includes travel times for the schools', verbose_name='Includes travel times'),
        ),
    ]
